version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: devsecops-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devsecops-node-app
    ports:
      - "3000:3000"
    env_file:
      - app/.env
    depends_on:
      - mongo

volumes:
  mongo-data:
